default: &defaults
  push_api_key: "<%= ENV['APPSIGNAL_PUSH_API_KEY'] %>"
  name: "Rake example"
  debug: true

development:
  <<: *defaults
  active: true

production:
  <<: *defaults
  active: true
