default: &default
  adapter: postgresql
  encoding: utf-8
  username: test
  password: test
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: rails_5_que_example_development

test:
  <<: *default
  database: rails_5_que_example_test

production:
  <<: *default
  database: rails_5_que_example_production
