# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6eccc3de7176cc0cc7e93e4e7bc1de2f01ce230687b62672ff9c2315d8f37fa325862f161b1292e281c6c0228c04ece1a671456c2f9cf09c81786e19f7fd780f

test:
  secret_key_base: 2cc3da1a5514d5ee63a69ce14be54abef09bbc5b6681f15772947dfdefc56ddd2894a6ac1652ea25769e3555783671ad846e046df7726eed1007ecba5056a0cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
